_wandb:
    value:
        cli_version: 0.23.1
        e:
            bb32d31myf28qg0mk2j0t2m5ltz5pafp:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "19327352832"
                codePath: train_audio_only.py
                codePathLocal: train_audio_only.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "432884862976"
                email: ak1825@g.rit.edu
                executable: /Users/ashu1069/Projects/transfusion-pytorch/.venv/bin/python3
                git:
                    commit: 1867a98d9ec80a8ed8b641ca2806d7bd66ec47fb
                    remote: https://github.com/ashu1069/transfusion-pytorch.git
                host: Ashutoshs-MacBook-Pro.local
                memory:
                    total: "19327352832"
                os: macOS-14.6-arm64-arm-64bit
                program: /Users/ashu1069/Projects/transfusion-pytorch/train_audio_only.py
                python: CPython 3.12.9
                root: /Users/ashu1069/Projects/transfusion-pytorch
                startedAt: "2026-01-22T16:46:35.848956Z"
                writerId: bb32d31myf28qg0mk2j0t2m5ltz5pafp
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 16
            "4": 3.12.9
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch:
    value: 16
lr:
    value: 5e-05
params:
    value: 401608528
steps:
    value: 50000
